name: Tag commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
      
      - name: Github Tag with semantic versioning
        uses: hennejg/github-tag-action@v4.3.1
