name: Create Release
on:
  push:
    tags:
      - '*'
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:        
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* .github'
     
      - uses: actions/checkout@master
          
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          makeLatest: true
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
